/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author Felipe
 */
public class frmCalculadora extends javax.swing.JFrame {

    String v1, v2, conteudo, sinal;
    Double resultado;
    
    public frmCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMostra = new javax.swing.JTextField();
        btnIgual = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnMais = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setFocusCycleRoot(false);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(227, 240));
        setMinimumSize(new java.awt.Dimension(227, 240));
        setPreferredSize(new java.awt.Dimension(227, 240));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMostra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMostra.setDropMode(javax.swing.DropMode.INSERT);
        txtMostra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMostraFocusGained(evt);
            }
        });
        txtMostra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMostraActionPerformed(evt);
            }
        });
        getContentPane().add(txtMostra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        getContentPane().add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 30));

        btnDividir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 40, 30));

        btnMais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMais.setText("+");
        btnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisActionPerformed(evt);
            }
        });
        getContentPane().add(btnMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        btnMenos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 40, 30));

        btnMultiplicar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMultiplicar.setText("*");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 30));

        btnSair.setText("SAIR");
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 70, 30));

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String Operacoes(String v1, String v2, String sinal){
        Double resultadoCalc = 0.0;
        String resposta;
        
        if(sinal.equals("+"))
        {
            resultadoCalc = Double.parseDouble(v1)+Double.parseDouble(v2);
        }
        if(sinal.equals("-"))
        {
            resultadoCalc = Double.parseDouble(v1)-Double.parseDouble(v2);
        }
        if(sinal.equals("*"))
        {
            resultadoCalc = Double.parseDouble(v1)*Double.parseDouble(v2);
        }
        if(sinal.equals("/"))
        {
            resultadoCalc = Double.parseDouble(v1)/Double.parseDouble(v2);
        }
        
        resposta = resultadoCalc.toString();
        return resposta;
    }
    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        
        if(!txtMostra.getText().equals("")){
            v1 = txtMostra.getText();
            sinal = "/";
            txtMostra.setText("");
        }
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        
        if(!txtMostra.getText().equals("")){
            v1 = txtMostra.getText();
            sinal = "-";
            txtMostra.setText("");
        }
    }//GEN-LAST:event_btnMenosActionPerformed

    private void txtMostraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMostraActionPerformed
        
    }//GEN-LAST:event_txtMostraActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        txtMostra.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisActionPerformed
        
        if(!txtMostra.getText().equals("")){
            v1 = txtMostra.getText();
            sinal = "+";
            txtMostra.setText("");
        }
            
    }//GEN-LAST:event_btnMaisActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        
        if(!txtMostra.getText().equals("")){
            v1 = txtMostra.getText();
            sinal = "*";
            txtMostra.setText("");
        }
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        String resultadoFinal;
        v2 = txtMostra.getText();
        if(!v2.equals("")){
            resultadoFinal = Operacoes(v1, v2, sinal);
            txtMostra.setText(resultadoFinal);        
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void txtMostraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMostraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMostraFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnSair;
    private javax.swing.JTextField txtMostra;
    // End of variables declaration//GEN-END:variables
}
